export const SERVICE_TYPES = [
  { name: 'Supermarket', description: 'Grocery stores and supermarkets', icon: 'shopping-cart' },
  { name: 'Gas Station', description: 'Fuel stations and service centers', icon: 'gas-pump' },
  { name: 'Restaurant', description: 'Restaurants and dining establishments', icon: 'utensils' },
  { name: 'Pharmacy', description: 'Pharmacies and drugstores', icon: 'pills' },
  { name: 'Bank', description: 'Banks and financial institutions', icon: 'university' },
  { name: 'Hospital', description: 'Hospitals and medical centers', icon: 'hospital' },
  { name: 'Shopping Mall', description: 'Shopping centers and malls', icon: 'shopping-bag' },
  { name: 'Coffee Shop', description: 'Coffee shops and cafes', icon: 'coffee' },
  { name: 'ATM', description: 'Automated teller machines', icon: 'credit-card' },
  { name: 'School', description: 'Educational institutions', icon: 'graduation-cap' },
  { name: 'Library', description: 'Public and private libraries', icon: 'book' },
  { name: 'Gym', description: 'Fitness centers and gyms', icon: 'dumbbell' },
  { name: 'Hotel', description: 'Hotels and accommodations', icon: 'bed' },
  { name: 'Post Office', description: 'Postal services', icon: 'mail' },
  { name: 'Police Station', description: 'Law enforcement facilities', icon: 'shield' },
  { name: 'Fire Station', description: 'Fire department facilities', icon: 'fire' },
  { name: 'Park', description: 'Public parks and recreation areas', icon: 'tree' },
  { name: 'Cinema', description: 'Movie theaters and cinemas', icon: 'film' },
  { name: 'Beauty Salon', description: 'Hair and beauty services', icon: 'scissors' },
  { name: 'Car Repair', description: 'Automotive repair services', icon: 'wrench' },
];
